# 最小单位
# 定义蛇走的步数
STEP_NUM = 20
# 定义游戏屏幕的宽和高
GAME_COLUMN_NUM = 50
GAME_ROW_NUM = 31
GAME_WIDTH = GAME_COLUMN_NUM * STEP_NUM
GAME_HEIGHT = GAME_ROW_NUM * STEP_NUM

# 定义方向
NORTH = 0
SOUTH = 1
WEST = 2
EAST = 3
# 定义蛇头初始的位置和方向
HEAD_X = GAME_WIDTH * .5
HEAD_Y = 15 * STEP_NUM
HEAD_DIRECTION = NORTH
# 定义游戏的四种状态
GAME_START = 0
GAME_RUNNING = 1
GAME_STOP = 2
